ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS emi_amount        NUMERIC  DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS emi_start_date    DATE;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS emi_tenure_months INTEGER  DEFAULT 0;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS emi_description   TEXT     DEFAULT '';
